version: '3.8'

volumes:
  authup:

services:
  authup:
    image: authup/authup:latest
    pull_policy: always
    container_name: server-core
    restart: unless-stopped
    volumes:
      - authup:/usr/src/writable
    ports:
      - ${AUTHUP_PUBLIC_PORT:-4001}:3000
    command: server/core start
    environment:
      - PUBLIC_URL=${AUTHUP_PUBLIC_URL:-https://dnpm.bwhealthcloud.de/auth/}
    networks:
      dnpm:

  portal:
    image: ghcr.io/kohlbacherlab/dnpm-dip-portal:latest
    pull_policy: always
    container_name: portal
    restart: unless-stopped
    environment:
      - NUXT_PUBLIC_API_URL=${PORTAL_PUBLIC_URL:-https://dnpm.bwhealthcloud.de/api/}
    ports:
      - ${PORTAL_PUBLIC_PORT:-4000}:3000
    networks:
      dnpm:

  backend:
    image: ghcr.io/kohlbacherlab/dnpm-dip-backend:latest
    # Optionally set system UserID with corresponding access permissions to data persistence directory
    #user: "UserID"
    ports:
      - ${BACKEND_PUBLIC_PORT:-9000}:9000
    environment:
      - RD_RANDOM_DATA=50
      - MTB_RANDOM_DATA=50
      - HOST_BASEURL=${BACKEND_PUBLIC_URL:-http://localhost:9000}
      - CONNECTOR_TYPE=peer2peer   # "broker" (default) | "peer2peer"
    volumes:
      - /PATH/TO/CONFIG_DIR:/dnpm_config     #TODO
      - /PATH/TO/PERSISTENCE_DIR:/dnpm_data  #TODO
    networks:
      dnpm:


networks:
  dnpm:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dnpm
    ipam:
      driver: default
      config:
        - subnet: 172.23.1.0/24
